[meta]
name     = "MLHook & Event Inspector"
author   = "XertroV"
category = "MLHook"
version  = "0.3.2-pre"

[script]
#__DEFINES__
module = "MLHook"
exports = [ "Exports/Export.as" ] # no src/ prefix b/c of build.sh
shared_exports = [ "Exports/ExportShared.as" ] # no src/ prefix b/c of build.sh
# dependencies = [ 'MLHook' ]
